services:
  postgres:
    image: postgres:18.0
    container_name: auth-comparison-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: auth-comparison-keycloak
    command: start-dev --import-realm
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
      - ./keycloak/certs:/opt/keycloak/certs

volumes:
  postgres_data: